
import { User } from '../types/auth';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@voli.com',
    name: 'Admin User',
    role: 'admin',
    avatarUrl: 'https://i.pravatar.cc/150?img=68',
    organization: 'VOLI Headquarters',
    organizationId: 'org1',
    companyLogo: '/voli-logo.png',
    points: 1250,
    badges: ['Founder', 'Impact Leader', 'Community Builder'],
    level: 5,
    joinedAt: '2023-01-15T10:00:00Z',
    lastActive: new Date().toISOString(),
    location: 'Melbourne',
    coordinates: [144.9631, -37.8136]
  },
  {
    id: '2',
    email: 'user@voli.com',
    name: 'Demo User',
    role: 'user',
    avatarUrl: 'https://i.pravatar.cc/150?img=65',
    organization: 'Demo Company',
    organizationId: 'org1',
    points: 450,
    badges: ['Newcomer', 'Volunteer'],
    level: 2,
    joinedAt: '2023-03-20T14:30:00Z',
    lastActive: new Date().toISOString(),
    location: 'Melbourne',
    coordinates: [144.9339, -37.8230]
  },
  // Melbourne Team
  {
    id: '3',
    email: 'sarah.chen@voli.com',
    name: 'Sarah Chen',
    role: 'team_lead',
    avatarUrl: 'https://i.pravatar.cc/150?img=37',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 980,
    badges: ['Team Lead', 'Mentor'],
    level: 4,
    joinedAt: '2023-02-10T09:15:00Z',
    lastActive: new Date(Date.now() - 1800000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9511, -37.8150]
  },
  {
    id: '4',
    email: 'marcus.lee@voli.com',
    name: 'Marcus Lee',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 732,
    badges: ['Tech Guru', 'Event Organizer'],
    level: 3,
    joinedAt: '2023-03-05T11:45:00Z',
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9631, -37.8200]
  },
  {
    id: '5',
    email: 'olivia.wilson@voli.com',
    name: 'Olivia Wilson',
    role: 'designer',
    avatarUrl: 'https://i.pravatar.cc/150?img=23',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 645,
    badges: ['Design Star', 'Community Builder'],
    level: 3,
    joinedAt: '2023-03-15T10:30:00Z',
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9731, -37.8050]
  },
  {
    id: '6',
    email: 'liam.nguyen@voli.com',
    name: 'Liam Nguyen',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=53',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 580,
    badges: ['Code Wizard', 'Mentor'],
    level: 3,
    joinedAt: '2023-04-02T15:20:00Z',
    lastActive: new Date(Date.now() - 10800000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9831, -37.8130]
  },
  {
    id: '7',
    email: 'emma.patel@voli.com',
    name: 'Emma Patel',
    role: 'community_manager',
    avatarUrl: 'https://i.pravatar.cc/150?img=24',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 830,
    badges: ['Engagement Expert', 'Event Organizer'],
    level: 4,
    joinedAt: '2023-02-20T08:45:00Z',
    lastActive: new Date(Date.now() - 5400000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9931, -37.8236]
  },
  {
    id: '8',
    email: 'noah.sharma@voli.com',
    name: 'Noah Sharma',
    role: 'analyst',
    avatarUrl: 'https://i.pravatar.cc/150?img=60',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 510,
    badges: ['Data Master', 'Problem Solver'],
    level: 2,
    joinedAt: '2023-04-10T13:10:00Z',
    lastActive: new Date(Date.now() - 14400000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9331, -37.8336]
  },
  {
    id: '9',
    email: 'ava.mitchell@voli.com',
    name: 'Ava Mitchell',
    role: 'content_creator',
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 420,
    badges: ['Storyteller', 'Creative Mind'],
    level: 2,
    joinedAt: '2023-05-05T11:30:00Z',
    lastActive: new Date(Date.now() - 21600000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9531, -37.8036]
  },
  {
    id: '10',
    email: 'ethan.rodriguez@voli.com',
    name: 'Ethan Rodriguez',
    role: 'hr_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=42',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 690,
    badges: ['Talent Scout', 'Team Builder'],
    level: 3,
    joinedAt: '2023-03-22T09:50:00Z',
    lastActive: new Date(Date.now() - 28800000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9731, -37.8436]
  },
  {
    id: '11',
    email: 'sofia.kim@voli.com',
    name: 'Sofia Kim',
    role: 'marketing_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=25',
    organization: 'VOLI Melbourne',
    organizationId: 'org1',
    points: 560,
    badges: ['Brand Ambassador', 'Social Media Guru'],
    level: 3,
    joinedAt: '2023-04-15T14:25:00Z',
    lastActive: new Date(Date.now() - 43200000).toISOString(),
    location: 'Melbourne',
    coordinates: [144.9831, -37.8536]
  },
  
  // New York Team
  {
    id: '12',
    email: 'jackson.miller@voli.com',
    name: 'Jackson Miller',
    role: 'team_lead',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 920,
    badges: ['Team Lead', 'Innovation Champion'],
    level: 4,
    joinedAt: '2023-02-05T08:30:00Z',
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    location: 'New York',
    coordinates: [-73.9857, 40.7484]
  },
  {
    id: '13',
    email: 'isabella.garcia@voli.com',
    name: 'Isabella Garcia',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 785,
    badges: ['Code Architect', 'Problem Solver'],
    level: 3,
    joinedAt: '2023-03-12T10:45:00Z',
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    location: 'New York',
    coordinates: [-73.9957, 40.7384]
  },
  {
    id: '14',
    email: 'logan.brown@voli.com',
    name: 'Logan Brown',
    role: 'designer',
    avatarUrl: 'https://i.pravatar.cc/150?img=67',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 605,
    badges: ['UI Master', 'Creative Leader'],
    level: 3,
    joinedAt: '2023-04-08T14:15:00Z',
    lastActive: new Date(Date.now() - 10800000).toISOString(),
    location: 'New York',
    coordinates: [-73.9757, 40.7584]
  },
  {
    id: '15',
    email: 'mia.davis@voli.com',
    name: 'Mia Davis',
    role: 'marketing_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=19',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 540,
    badges: ['Marketing Maven', 'Growth Hacker'],
    level: 2,
    joinedAt: '2023-05-01T11:20:00Z',
    lastActive: new Date(Date.now() - 14400000).toISOString(),
    location: 'New York',
    coordinates: [-73.9657, 40.7684]
  },
  {
    id: '16',
    email: 'lucas.wilson@voli.com',
    name: 'Lucas Wilson',
    role: 'analyst',
    avatarUrl: 'https://i.pravatar.cc/150?img=62',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 490,
    badges: ['Data Scientist', 'Insight Generator'],
    level: 2,
    joinedAt: '2023-05-10T09:40:00Z',
    lastActive: new Date(Date.now() - 21600000).toISOString(),
    location: 'New York',
    coordinates: [-73.9557, 40.7784]
  },
  {
    id: '17',
    email: 'aria.thompson@voli.com',
    name: 'Aria Thompson',
    role: 'community_manager',
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 710,
    badges: ['Community Builder', 'Engagement Expert'],
    level: 3,
    joinedAt: '2023-03-25T13:50:00Z',
    lastActive: new Date(Date.now() - 28800000).toISOString(),
    location: 'New York',
    coordinates: [-74.0057, 40.7284]
  },
  {
    id: '18',
    email: 'mateo.johnson@voli.com',
    name: 'Mateo Johnson',
    role: 'content_creator',
    avatarUrl: 'https://i.pravatar.cc/150?img=54',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 470,
    badges: ['Content King', 'Creative Storyteller'],
    level: 2,
    joinedAt: '2023-05-15T15:30:00Z',
    lastActive: new Date(Date.now() - 43200000).toISOString(),
    location: 'New York',
    coordinates: [-73.9457, 40.7884]
  },
  {
    id: '19',
    email: 'emily.martin@voli.com',
    name: 'Emily Martin',
    role: 'hr_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=16',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 630,
    badges: ['Culture Champion', 'Talent Developer'],
    level: 3,
    joinedAt: '2023-04-05T08:20:00Z',
    lastActive: new Date(Date.now() - 86400000).toISOString(),
    location: 'New York',
    coordinates: [-73.9357, 40.7984]
  },
  {
    id: '20',
    email: 'aiden.murphy@voli.com',
    name: 'Aiden Murphy',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=69',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 520,
    badges: ['Backend Specialist', 'System Architect'],
    level: 2,
    joinedAt: '2023-05-05T10:10:00Z',
    lastActive: new Date(Date.now() - 172800000).toISOString(),
    location: 'New York',
    coordinates: [-73.9257, 40.8084]
  },
  {
    id: '21',
    email: 'amelia.lewis@voli.com',
    name: 'Amelia Lewis',
    role: 'designer',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    organization: 'VOLI New York',
    organizationId: 'org1',
    points: 550,
    badges: ['UX Innovator', 'Design Thinker'],
    level: 2,
    joinedAt: '2023-04-28T14:45:00Z',
    lastActive: new Date(Date.now() - 259200000).toISOString(),
    location: 'New York',
    coordinates: [-73.9157, 40.8184]
  },
  
  // London Team
  {
    id: '22',
    email: 'charlotte.jones@voli.com',
    name: 'Charlotte Jones',
    role: 'team_lead',
    avatarUrl: 'https://i.pravatar.cc/150?img=34',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 960,
    badges: ['Team Lead', 'Strategic Thinker'],
    level: 4,
    joinedAt: '2023-02-02T09:20:00Z',
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    location: 'London',
    coordinates: [-0.1278, 51.5074]
  },
  {
    id: '23',
    email: 'henry.taylor@voli.com',
    name: 'Henry Taylor',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=59',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 750,
    badges: ['Full Stack Expert', 'Technical Lead'],
    level: 3,
    joinedAt: '2023-03-08T11:15:00Z',
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    location: 'London',
    coordinates: [-0.1378, 51.5174]
  },
  {
    id: '24',
    email: 'eleanor.white@voli.com',
    name: 'Eleanor White',
    role: 'designer',
    avatarUrl: 'https://i.pravatar.cc/150?img=18',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 680,
    badges: ['Design Director', 'Visual Storyteller'],
    level: 3,
    joinedAt: '2023-03-20T10:50:00Z',
    lastActive: new Date(Date.now() - 10800000).toISOString(),
    location: 'London',
    coordinates: [-0.1478, 51.5274]
  },
  {
    id: '25',
    email: 'william.clark@voli.com',
    name: 'William Clark',
    role: 'marketing_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=61',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 590,
    badges: ['Digital Marketer', 'Campaign Strategist'],
    level: 3,
    joinedAt: '2023-04-12T15:40:00Z',
    lastActive: new Date(Date.now() - 14400000).toISOString(),
    location: 'London',
    coordinates: [-0.1578, 51.5374]
  },
  {
    id: '26',
    email: 'violet.moore@voli.com',
    name: 'Violet Moore',
    role: 'analyst',
    avatarUrl: 'https://i.pravatar.cc/150?img=26',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 530,
    badges: ['Business Intelligence', 'Financial Analyst'],
    level: 2,
    joinedAt: '2023-05-03T13:25:00Z',
    lastActive: new Date(Date.now() - 21600000).toISOString(),
    location: 'London',
    coordinates: [-0.1678, 51.5474]
  },
  {
    id: '27',
    email: 'james.allen@voli.com',
    name: 'James Allen',
    role: 'community_manager',
    avatarUrl: 'https://i.pravatar.cc/150?img=57',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 740,
    badges: ['Community Builder', 'Relationship Manager'],
    level: 3,
    joinedAt: '2023-03-15T08:55:00Z',
    lastActive: new Date(Date.now() - 28800000).toISOString(),
    location: 'London',
    coordinates: [-0.1778, 51.5574]
  },
  {
    id: '28',
    email: 'scarlett.young@voli.com',
    name: 'Scarlett Young',
    role: 'content_creator',
    avatarUrl: 'https://i.pravatar.cc/150?img=28',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 510,
    badges: ['Content Strategist', 'Creative Writer'],
    level: 2,
    joinedAt: '2023-05-08T14:10:00Z',
    lastActive: new Date(Date.now() - 43200000).toISOString(),
    location: 'London',
    coordinates: [-0.1878, 51.5674]
  },
  {
    id: '29',
    email: 'theodore.brown@voli.com',
    name: 'Theodore Brown',
    role: 'hr_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=52',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 670,
    badges: ['Talent Acquisition', 'Employee Experience'],
    level: 3,
    joinedAt: '2023-03-28T09:30:00Z',
    lastActive: new Date(Date.now() - 86400000).toISOString(),
    location: 'London',
    coordinates: [-0.1978, 51.5774]
  },
  {
    id: '30',
    email: 'penelope.harris@voli.com',
    name: 'Penelope Harris',
    role: 'developer',
    avatarUrl: 'https://i.pravatar.cc/150?img=29',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 560,
    badges: ['Mobile Developer', 'API Specialist'],
    level: 2,
    joinedAt: '2023-04-25T11:35:00Z',
    lastActive: new Date(Date.now() - 172800000).toISOString(),
    location: 'London',
    coordinates: [-0.2078, 51.5874]
  },
  {
    id: '31',
    email: 'arthur.wilson@voli.com',
    name: 'Arthur Wilson',
    role: 'designer',
    avatarUrl: 'https://i.pravatar.cc/150?img=51',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 580,
    badges: ['Motion Designer', 'Brand Identity'],
    level: 3,
    joinedAt: '2023-04-18T15:20:00Z',
    lastActive: new Date(Date.now() - 259200000).toISOString(),
    location: 'London',
    coordinates: [-0.2178, 51.5974]
  },
  // More staff with locations
  {
    id: '32',
    email: 'grace.martinez@voli.com',
    name: 'Grace Martinez',
    role: 'marketing_specialist',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    organization: 'VOLI London',
    organizationId: 'org1',
    points: 520,
    badges: ['Social Media Expert', 'Event Planner'],
    level: 2,
    joinedAt: '2023-05-05T13:40:00Z',
    lastActive: new Date(Date.now() - 345600000).toISOString(),
    location: 'London',
    coordinates: [-0.1258, 51.5154]
  }
];

// Utility function to get user by id
export const getUserById = (id: string): User | undefined => {
  return mockUsers.find(user => user.id === id);
};
